<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinApp.Forecasting\FinApp.Forecasting.csproj" />
    <ProjectReference Include="..\FinApp.Kernel\FinApp.Kernel.csproj" />
  </ItemGroup>

</Project>
