// <auto-generated />
using System;
using FinApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinApp.Persistence.Migrations
{
    [DbContext(typeof(FinAppDbContext))]
    [Migration("20260723094853_AddSnapshotVersionConcurrencyToken")]
    partial class AddSnapshotVersionConcurrencyToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FinApp.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Accounts.AccountMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlertThreshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Allocated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnEveryExpense")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnBehalfOfOtherAccount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SettledAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettledFromAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettledToAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettlementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceSavingCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.ExternalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("ExternalTransfers", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Funds", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.FundTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromFundId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToFundId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("FundTransfers", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Paid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("Contributions", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.ContributionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ContributionCategories", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.InitialBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Informative")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("InitialBalances", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarriedIn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("From")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Periods", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Savings.SavingAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BudgetCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SavingCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceExpenseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransferPairId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("SavingAllocations", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Savings.SavingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlertThreshold")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnMilestone")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SavingCategories", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Sharing.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("AccountId", "InvitedUserId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FinApp.Persistence.AccountSnapshotRow", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSnapshots", (string)null);
                });

            modelBuilder.Entity("FinApp.Domain.Accounts.AccountMember", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("Members")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Budget", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("Budgets")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Category", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("Categories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Budgeting.Expense", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("Expenses")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.ExternalTransfer", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("ExternalTransfers")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.Fund", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("Funds")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Funds.FundTransfer", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("FundTransfers")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.Contribution", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("Contributions")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.ContributionCategory", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("ContributionCategories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.InitialBalance", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("InitialBalances")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Periods.Period", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("Periods")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Savings.SavingAllocation", b =>
                {
                    b.HasOne("FinApp.Domain.Periods.Period", null)
                        .WithMany("SavingAllocations")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Savings.SavingCategory", b =>
                {
                    b.HasOne("FinApp.Domain.Accounts.Account", null)
                        .WithMany("SavingCategories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinApp.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ContributionCategories");

                    b.Navigation("Funds");

                    b.Navigation("Members");

                    b.Navigation("Periods");

                    b.Navigation("SavingCategories");
                });

            modelBuilder.Entity("FinApp.Domain.Periods.Period", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Contributions");

                    b.Navigation("Expenses");

                    b.Navigation("ExternalTransfers");

                    b.Navigation("FundTransfers");

                    b.Navigation("InitialBalances");

                    b.Navigation("SavingAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
